### ISSUE TITLE
Error: Option `imageA` must either be a String, Buffer or Rembrandt.Image.

### ISSUE THREAD

**Issue by wanderdevof** [arc298/tiktok-captcha-solver#6]
![image](https://user-images.githubusercontent.com/41404725/139574203-fb0c46d3-b57a-4523-998e-19bf49d88400.png)

**Comment by malec** [comment]
I fixed this issue, check out my fork at https://github.com/malec/tiktok-captcha-solver

**Comment by arc298** [comment]
Fixed in PR #7. Released in v0.0.7

**Comment by Davpyu** [comment]
im still getting this error eventhough i have upgrade the package to v0.0.7
